path = r"C:\Projects\studyscrum\README.md"

content = (
    "# StudyScrum\n"
    "\n"
    "A cloud-native project management platform built for academic Scrum teams.\n"
    "Manage projects, sprints, and tickets with real-time collaboration.\n"
    "\n"
    "---\n"
    "\n"
    "## Tech Stack\n"
    "\n"
    "### Backend\n"
    "- **Java 21** (Eclipse Temurin) + **Spring Boot 3.5.0**\n"
    "- **Spring Cloud 2025.0.2** (Eureka, Gateway)\n"
    "- **Maven 3.9**\n"
    "- **MongoDB 7.0** - primary database\n"
    "- **Redis 7.2** - pub/sub messaging\n"
    "- **Spring WebSocket + STOMP** - real-time notifications\n"
    "- **Spring Security + JWT** (jjwt 0.12.6) + **Google OAuth2**\n"
    "- **Spring Cloud Gateway** (WebFlux)\n"
    "- **Spring Cloud Netflix Eureka** - service discovery\n"
    "\n"
    "### Frontend\n"
    "- **React 18** + **TypeScript** + **Vite 8**\n"
    "- **Tailwind CSS v4**\n"
    "- **React Router v6**\n"
    "- **Axios** - HTTP client with JWT interceptors\n"
    "- **@stomp/stompjs** + **sockjs-client** - WebSocket client\n"
    "\n"
    "### Infrastructure\n"
    "- **Docker** + **Docker Compose v2** - local development\n"
    "- **Kubernetes** - production orchestration (WIP)\n"
    "- **GitHub Actions** - CI/CD (WIP)\n"
    "- **Prometheus + Grafana** - observability (WIP)\n"
    "\n"
    "---\n"
    "\n"
    "## Microservices\n"
    "\n"
    "| Service | Port | Description |\n"
    "|---------|------|-------------|\n"
    "| eureka-server | 8761 | Service discovery and registry |\n"
    "| identity-service | 8081 | Google OAuth2 + JWT authentication |\n"
    "| api-gateway | 8080 | Routing, JWT validation, CORS |\n"
    "| project-service | 8082 | Project and member management |\n"
    "| sprint-service | 8083 | Sprint lifecycle + burndown tracking |\n"
    "| ticket-service | 8084 | Kanban tickets (User Story / Task / Bug) |\n"
    "| notification-service | 8085 | WebSocket STOMP + Redis pub/sub |\n"
    "| frontend | 5173 | React SPA (dev) / 80 (Docker/Nginx) |\n"
    "\n"
    "---\n"
    "\n"
    "## Prerequisites\n"
    "\n"
    "- Java 21 (Eclipse Temurin) with JAVA_HOME set\n"
    "- Maven 3.9+\n"
    "- Node.js 24 + npm\n"
    "- Docker Desktop with Docker Compose v2\n"
    "- Git 2.x\n"
    "\n"
    "---\n"
    "\n"
    "## Quick Start with Docker\n"
    "\n"
    "### 1. Clone the repository\n"
    "\n"
    "```bash\n"
    "git clone https://github.com/USERNAME/studyscrum.git\n"
    "cd studyscrum\n"
    "```\n"
    "\n"
    "### 2. Create environment file\n"
    "\n"
    "```bash\n"
    "cp .env.example .env\n"
    "```\n"
    "\n"
    "Edit `.env` with your values:\n"
    "\n"
    "```env\n"
    "GOOGLE_CLIENT_ID=your-google-client-id\n"
    "GOOGLE_CLIENT_SECRET=your-google-client-secret\n"
    "JWT_SECRET=your-jwt-secret-min-256-bits\n"
    "```\n"
    "\n"
    "### 3. Build and start all services\n"
    "\n"
    "```bash\n"
    "docker compose up --build -d\n"
    "```\n"
    "\n"
    "### 4. Verify all services are running\n"
    "\n"
    "```bash\n"
    "docker compose ps\n"
    "```\n"
    "\n"
    "### 5. Open the app\n"
    "\n"
    "- Frontend: http://localhost:5173\n"
    "- Eureka Dashboard: http://localhost:8761\n"
    "- API Gateway: http://localhost:8080\n"
    "\n"
    "---\n"
    "\n"
    "## Quick Start for Local Development\n"
    "\n"
    "### 1. Start infrastructure only\n"
    "\n"
    "```bash\n"
    "docker compose up -d mongodb redis\n"
    "```\n"
    "\n"
    "### 2. Set environment variables (PowerShell)\n"
    "\n"
    "```powershell\n"
    '$env:GOOGLE_CLIENT_ID="your-google-client-id"\n'
    '$env:GOOGLE_CLIENT_SECRET="your-google-client-secret"\n'
    '$env:JWT_SECRET="your-jwt-secret-min-256-bits"\n'
    "```\n"
    "\n"
    "### 3. Start services in order\n"
    "\n"
    "Each in a separate terminal:\n"
    "\n"
    "```powershell\n"
    "# Terminal 1\n"
    "cd eureka-server; mvn spring-boot:run\n"
    "\n"
    "# Terminal 2\n"
    "cd identity-service; mvn spring-boot:run\n"
    "\n"
    "# Terminal 3\n"
    "cd api-gateway; mvn spring-boot:run\n"
    "\n"
    "# Terminal 4\n"
    "cd project-service; mvn spring-boot:run\n"
    "\n"
    "# Terminal 5\n"
    "cd sprint-service; mvn spring-boot:run\n"
    "\n"
    "# Terminal 6\n"
    "cd ticket-service; mvn spring-boot:run\n"
    "\n"
    "# Terminal 7\n"
    "cd notification-service; mvn spring-boot:run\n"
    "\n"
    "# Terminal 8\n"
    "cd frontend; npm install; npm run dev\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## Google OAuth2 Setup\n"
    "\n"
    "1. Go to Google Cloud Console: https://console.cloud.google.com\n"
    "2. Create a new project or select existing\n"
    "3. Enable Google+ API\n"
    "4. Create OAuth2 credentials (Web application)\n"
    "5. Add authorized redirect URIs:\n"
    "   - http://localhost:8081/login/oauth2/code/google\n"
    "   - http://localhost:8080/login/oauth2/code/google\n"
    "6. Add test users in OAuth consent screen\n"
    "7. Copy Client ID and Client Secret to .env\n"
    "\n"
    "---\n"
    "\n"
    "## Authentication Flow\n"
    "\n"
    "```\n"
    "1. User clicks Continue with Google\n"
    "2. Browser -> GET /login/oauth2/authorization/google\n"
    "3. API Gateway forwards to Identity Service (hardcoded URL, not via Eureka)\n"
    "4. Identity Service redirects to Google\n"
    "5. Google authenticates and redirects back to:\n"
    "   http://localhost:8081/login/oauth2/code/google\n"
    "6. Identity Service creates/updates User in MongoDB\n"
    "7. Identity Service generates:\n"
    "   - JWT access token (24h)\n"
    "   - JWT refresh token (7 days)\n"
    "8. Redirect to frontend:\n"
    "   http://localhost:5173/auth/callback?accessToken=...&refreshToken=...\n"
    "9. Frontend stores tokens in localStorage\n"
    "10. Frontend calls GET /auth/me to load user profile\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## Real-time Notifications Flow\n"
    "\n"
    "```\n"
    "1. Frontend connects: ws://localhost:8085/ws?token=JWT\n"
    "2. WebSocketAuthInterceptor validates JWT at handshake\n"
    "3. Frontend subscribes to: /topic/project/{projectId}\n"
    "4. Any service publishes to Redis: notifications:{projectId}\n"
    "5. RedisMessageSubscriber receives message from Redis\n"
    "6. Message forwarded via STOMP to all subscribed clients\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## API Endpoints\n"
    "\n"
    "### Identity Service\n"
    "\n"
    "| Method | Path | Auth | Description |\n"
    "|--------|------|------|-------------|\n"
    "| GET | /auth/me | JWT | Get current user profile |\n"
    "| POST | /auth/refresh | - | Refresh access token |\n"
    "\n"
    "### Project Service\n"
    "\n"
    "| Method | Path | Auth | Description |\n"
    "|--------|------|------|-------------|\n"
    "| GET | /projects | JWT | List user projects |\n"
    "| POST | /projects | JWT | Create project |\n"
    "| GET | /projects/{id} | JWT | Get project by ID |\n"
    "| POST | /projects/{id}/members | JWT | Add member to project |\n"
    "\n"
    "### Sprint Service\n"
    "\n"
    "| Method | Path | Auth | Description |\n"
    "|--------|------|------|-------------|\n"
    "| GET | /sprints/{projectId} | JWT | List sprints |\n"
    "| POST | /sprints/{projectId} | JWT | Create sprint |\n"
    "| GET | /sprints/{projectId}/{sprintId} | JWT | Get sprint |\n"
    "| PATCH | /sprints/{projectId}/{sprintId}/activate | JWT | Activate sprint |\n"
    "| PATCH | /sprints/{projectId}/{sprintId}/complete | JWT | Complete sprint |\n"
    "| PATCH | /sprints/{projectId}/{sprintId}/progress | JWT | Update progress |\n"
    "| POST | /sprints/{projectId}/{sprintId}/snapshot | JWT | Add burndown snapshot |\n"
    "| GET | /sprints/{projectId}/velocity | JWT | Get velocity |\n"
    "\n"
    "### Ticket Service\n"
    "\n"
    "| Method | Path | Auth | Description |\n"
    "|--------|------|------|-------------|\n"
    "| GET | /tickets/{projectId} | JWT | List project tickets |\n"
    "| POST | /tickets/{projectId} | JWT | Create ticket |\n"
    "| GET | /tickets/{projectId}/sprint/{sprintId} | JWT | List sprint tickets |\n"
    "| GET | /tickets/{projectId}/{ticketId} | JWT | Get ticket |\n"
    "| PATCH | /tickets/{projectId}/{ticketId} | JWT | Update ticket |\n"
    "| PATCH | /tickets/{projectId}/{ticketId}/move | JWT | Move ticket in Kanban |\n"
    "| PATCH | /tickets/{projectId}/{ticketId}/assign-sprint | JWT | Assign to sprint |\n"
    "| PATCH | /tickets/{projectId}/{ticketId}/remove-sprint | JWT | Remove from sprint |\n"
    "| DELETE | /tickets/{projectId}/{ticketId} | JWT | Delete ticket |\n"
    "\n"
    "### Notification Service\n"
    "\n"
    "| Method | Path | Auth | Description |\n"
    "|--------|------|------|-------------|\n"
    "| POST | /notifications/publish | JWT | Publish notification |\n"
    "| WS | ws://localhost:8085/ws?token=JWT | JWT | WebSocket connection |\n"
    "\n"
    "---\n"
    "\n"
    "## Project Structure\n"
    "\n"
    "```\n"
    "studyscrum/\n"
    "├── eureka-server/          # Spring Cloud Eureka Server\n"
    "├── identity-service/       # Authentication + JWT + Google OAuth2\n"
    "├── api-gateway/            # Spring Cloud Gateway + JWT filter\n"
    "├── project-service/        # Project + member management\n"
    "├── sprint-service/         # Sprint lifecycle + burndown\n"
    "├── ticket-service/         # Kanban tickets\n"
    "├── notification-service/   # WebSocket STOMP + Redis pub/sub\n"
    "├── frontend/               # React 18 + TypeScript + Vite\n"
    "├── k8s/                    # Kubernetes manifests (WIP)\n"
    "├── .github/                # GitHub Actions workflows (WIP)\n"
    "├── docker-compose.yml      # Full local stack\n"
    "├── .env.example            # Environment variables template\n"
    "└── README.md\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## Environment Variables\n"
    "\n"
    "| Variable | Required | Description |\n"
    "|----------|----------|-------------|\n"
    "| GOOGLE_CLIENT_ID | Yes | Google OAuth2 Client ID |\n"
    "| GOOGLE_CLIENT_SECRET | Yes | Google OAuth2 Client Secret |\n"
    "| JWT_SECRET | Yes | JWT signing secret (min 256 bits) |\n"
    "\n"
    "---\n"
    "\n"
    "## Known Constraints\n"
    "\n"
    "- Google OAuth2 redirect URIs are hardcoded to localhost - update for production\n"
    "- WebSocket connection is direct to port 8085 - not proxied through Gateway (WebFlux limitation)\n"
    "- OAuth2 routes /login/** and /oauth2/** are hardcoded in Gateway - not via Eureka\n"
    "- MongoDB runs as single node locally - ReplicaSet required for production transactions\n"
    "- JWT secret must be the same across all services that validate tokens\n"
    "\n"
    "---\n"
    "\n"
    "## Completed Phases\n"
    "\n"
    "- Phase 0 - Project setup and monorepo structure\n"
    "- Phase 1 - Identity Service skeleton\n"
    "- Phase 2 - Google OAuth2 + JWT\n"
    "- Phase 3 - Eureka Server\n"
    "- Phase 4 - API Gateway\n"
    "- Phase 5 - Project Service\n"
    "- Phase 6 - Sprint Service (burndown + velocity)\n"
    "- Phase 7 - Ticket Service (Kanban board)\n"
    "- Phase 8 - Notification Service (WebSocket STOMP + Redis pub/sub)\n"
    "- Phase 9 - Frontend React (auth flow, dashboard, Kanban board)\n"
    "- Phase 10 - Docker multi-stage builds + Compose stack\n"
    "\n"
    "## Remaining Phases\n"
    "\n"
    "- Phase 11 - Kubernetes local with kind\n"
    "- Phase 12 - MongoDB ReplicaSet on Kubernetes\n"
    "- Phase 13 - Cluster provisioning on RaaS-IS (OpenStack)\n"
    "- Phase 14 - Production deploy on RaaS-IS\n"
    "- Phase 15 - CI/CD with GitHub Actions\n"
    "- Phase 16 - SonarQube\n"
    "- Phase 17 - Observability with Prometheus + Grafana\n"
    "- Phase 18 - Final polish, OpenAPI on SwaggerHub, demo\n"
    "\n"
    "---\n"
    "\n"
    "## Built With\n"
    "\n"
    "StudyScrum is a university cloud computing project demonstrating microservices\n"
    "architecture, containerization, and real-time collaboration.\n"
)

with open(path, "w", encoding="utf-8") as f:
    f.write(content)

print("README.md generat cu succes la: " + path)
